### PR TITLE
Fix: CloudShell read-only authorization is not automatically revoked

### LINKED ISSUE #4489: CloudShell read-only authorization is not automatically revoked.
**Describe the bug**

If a user has read-only permission in a project, when he first opens the CloudShell, the role binding will be created. But if remove this user from the project, the role binding still exists. So, this user still can view the resource in the project via CloudShell.

image

**KubeVela Version**

1.5.0-beta.4

### PR DESCRIPTION
**Pull request by barnettZQG**
Signed-off-by: barnettZQG <barnett.zqg@gmail.com>

### Description of your changes

The role is only bound to the group, the user is bound to the group and gets permissions. the relationship between the user and the group save to the cert in the Kube config, which will be updated before the cloud shell environment is created.

Fixes #4489

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### Special notes for your reviewer

/cc @wonderflow

### CODE REVIEW

File: pkg/apiserver/interfaces/api/cloudshell.go [hunk 1]
```diff
@@ -61,6 +61,14 @@ func (c *CloudShellAPIInterface) GetWebServiceRoute() *restful.WebService {
 		Returns(400, "Bad Request", bcode.Bcode{}).
 		Writes(apis.CloudShellPrepareResponse{}).Do(returns200, returns500))
 
+	ws.Route(ws.DELETE("/").To(c.destroyCloudShell).
```
Comment (wonderflow) [inline pkg/apiserver/interfaces/api/cloudshell.go:64]: who will invoke this API to detroy？

File: pkg/apiserver/utils/auth.go [hunk 2]
```diff
@@ -32,6 +32,9 @@ import (
 // KubeVelaProjectGroupPrefix the prefix kubevela project
 const KubeVelaProjectGroupPrefix = "kubevela:project:"
 
+// KubeVelaProjectReadGroupPrefix the prefix kubevela project group that only has the read permissions
+const KubeVelaProjectReadGroupPrefix = "kubevela:project-read:"
```
Comment (wonderflow) [inline pkg/apiserver/utils/auth.go:36]:
```suggestion
const KubeVelaProjectReadGroupPrefix = "kubevela:projectRO:"
```

File: pkg/apiserver/interfaces/api/cloudshell.go (hunk 1 above)
Comment (barnettZQG) [reply pkg/apiserver/interfaces/api/cloudshell.go:64]: Users could destroy the cloud shell environment and recreate it, this could get the new permissions.

File: pkg/apiserver/utils/auth.go (hunk 2 above)
Comment (barnettZQG) [reply pkg/apiserver/utils/auth.go:36]: The name cannot have capital letters.

Comment (wonderflow) [reply pkg/apiserver/utils/auth.go:36]: kubevela:project-ro:

**Review by wonderflow — APPROVED** [review]

**Review by yangsoon — APPROVED** [review]
