### PR TITLE
Fix: list addon commond displays only the first 20 entries when addon  registry is gitlab type

### LINKED ISSUE #5998: list addon commond displays only the first 20 entries when addon registry is gitlab type
**Describe the bug**
list addon commond displays only the first 20 entries when addon registry is gitlab type

**To Reproduce**

1. add gitlab type registry
2. vela addon ls

**Expected behavior**

show all the addons in gitlab repo

**Screenshots**

image

**KubeVela Version**
1.6.5

### PR DESCRIPTION
**Pull request by zhaohuiweixiao**
### Summary
:recycle::sparkles::zap:

Fix GitLab addon metadata listing to support keyset pagination. Update `ListAddonMeta` function in `pkg/addon/reader_gitlab.go` to fetch and concatenate all pages of the tree.

> _`ListAddonMeta` changed_
> _To fetch all tree pages_
> _Looping through keysets_

### Walkthrough
* Implement keyset-based pagination for GitLab ListTree API ([link](https://github.com/kubevela/kubevela/pull/5999/files?diff=unified&w=0#diff-7f81d0811dc0f7bbfd3e715748d66b540d7106a5d0e8ad09eb0b042e4b7199d4L87-R105))

Fixes #5998 

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

add gitlab type registry
vela addon ls

### Special notes for your reviewer

@wangyikewxgm

### CODE REVIEW

File: references/cli/addon-registry.go [hunk 1]
```diff
@@ -72,8 +72,10 @@ func NewAddAddonRegistryCommand(c common.Args, ioStreams cmdutil.IOStreams) *cob
 		Short: "Add an addon registry.",
 		Long:  "Add an addon registry.",
 		Example: `add a helm repo registry: vela addon registry add --type=helm my-repo --endpoint=<URL>
-add a github registry: vela addon registry add my-repo --type git --endpoint=<URL> --path=<ptah> --gitToken=<git token>" 
-add a gitlab registry: vela addon registry add my-repo --type gitlab --endpoint=<URL> --gitlabRepoName=<repoName> --path=<path> --gitToken=<git token>`,
+add a github registry: vela addon registry add my-repo --type git --endpoint=<URL> --path=<path> --gitToken=<git token>
+add a specified github registry: vela addon registry add my-repo --type git --endpoint=https://github.com/kubevela/catalog --path=addons --gitToken=<git token>
+add a gitlab registry: vela addon registry add my-repo --type gitlab --endpoint=<URL> --gitlabRepoName=<repoName> --path=<path> --gitToken=<git token>
+addon a specified gitlab registry: vela addon registry add my-repo --type gitlab --endpoint=http://gitlab.cmss.com/xxx/catalog --path=addons --gitlabRepoName=catalog --gitToken=<git token>`,
```
Comment (wangyikewxgm) [inline references/cli/addon-registry.go:78]:
```suggestion
add a specified gitlab registry: vela addon registry add my-repo --type gitlab --endpoint=http://gitlab.cmss.com/xxx/catalog --path=addons --gitlabRepoName=catalog --gitToken=<git token>`,
```

**Review by wangyikewxgm — APPROVED** [review]
LGTM, good job!
