### PR TITLE
Fix: vela addon upgrade missing the history args

### LINKED ISSUE #4311: `vela addon upgrade` missing the history args
**Describe the bug**

The different `vela addon upgrade`  with `vela addon enable` should keep the history args and support override it with new args. But, currently, it is not.

**To Reproduce**

1. `vela addon enable velaux --version=v1.4.2 repo=acr.kubevela.net`
2. `vela addon upgrade velaux --version=v1.4.5`

The `repo=acr.kubevela.net` will be missing

**KubeVela Version**

1.4.5

### PR DESCRIPTION
**Pull request by StevenLeiZhang**
Signed-off-by: StevenLeiZhang <zhangleiic@163.com>

### Description of your changes

Fixes #4311 
How to fix it:
Merge legacy parameters and new input parameters.
1. if legacy parameters do not exist, use new parameters
2. if legacy parameters exists, merge them and new parameter overwrite the legacy one

I have:

- [ ] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

File: pkg/addon/addon.go [hunk 1]
```diff
@@ -1596,3 +1596,41 @@ func PackageAddon(addonDictPath string) (string, error) {
...
+	if args == nil && legacyParams == nil {
+		return args, nil
+	}
+	r := make(map[string]interface{})
+	for k, v := range legacyParams {
+		r[k] = v
+	}
+	// override the legacyParams with new args for the same key
+	for k, v := range args {
+		r[k] = v
```
Comment (charlie0129) [inline pkg/addon/addon.go:1633]: What about nested arguments like this? It seems that this can only handle top-level arguments.

Old:
```json5
foo: {
  bar: "some"
  bar2: "some2"
}
```

New:
```json5
foo: {
  bar2: "some2new"
}
```

Now the old `foo.bar` will be gone, which is not an intended behavior.

Comment (StevenLeiZhang) [reply pkg/addon/addon.go:1633]: when user enable/upgrade addon, his command looks like this:
```
vela addon enable velaux --version=v1.4.5 repo=hub.vela.com  serviceType=NodePort imagePullSecrets={test-hub}
```
even "{test-hub}" looks like one object,  but it is the value of "imagePullSecrets" actually.
So I want to merge args, and overwrite the "value" without  recursively deep-merge .

Comment (charlie0129) [reply pkg/addon/addon.go:1633]: The `xxx=xxx` portion is a Helm strval. You can see it here:

https://github.com/kubevela/kubevela/blob/203a7dfbdab5f966d7085b21e090781395c79205/references/cli/addon.go#L317-L319

So the user can do something like this: `foo.bar=whatever` to define nested args.

An example is:

`vela addon enable chartmuseum persistence.enabled=true persistence.pvcName=myname`

Comment (StevenLeiZhang) [reply pkg/addon/addon.go]: updated

File: pkg/addon/addon_test.go [hunk 2]
```diff
@@ -1260,3 +1260,100 @@ func TestGenerateAnnotation(t *testing.T) {
...
+			mergedArgs: "{\"p1\":{\"p12\":\"p12-v2\",\"p13\":\"p13-v1\"}}",
+		},
+		{
+			// there is not new args
+			name:       "addon6",
+			legacyArgs: "{\"clusters\":[\"\"],\"p1\":{\"p11\":\"p11-v1\",\"p12\":\"p12-v1\"}}",
+			args:       nil,
+			mergedArgs: "{\"clusters\":[\"\"],\"p1\":{\"p11\":\"p11-v1\",\"p12\":\"p12-v1\"}}",
+		},
+	}
```
Comment (wonderflow) [inline pkg/addon/addon_test.go:1333]: please add a case to test the override scenario

Comment (wonderflow) [reply pkg/addon/addon_test.go:1333]: nested + override

Comment (StevenLeiZhang) [reply pkg/addon/addon_test.go:1333]: please refer to Line 1304.  p1.p11 keeps legacy value, p1.p12 will overwrite legacy value, p1.p13 is one new input parameter.

**Comment by charlie0129** [comment]
Great, please let the user know that the arguments will be merged in the command help text.

File: pkg/addon/addon_test.go (hunk 2 above)
Comment (wonderflow) [reply pkg/addon/addon_test.go:1333]: sorry, I missed that case, thanks

**Review by wonderflow — APPROVED** [review]
great job

**Comment by StevenLeiZhang** [comment]
> Great, please let the user know that the arguments will be merged in the command help text.

Done

**Review by Somefive — APPROVED** [review]
