### PR TITLE
Fix: vela show panic for component markdown format

### LINKED ISSUE #4697: [Bug] vela show webservice --format markdown error
**Describe the bug**

`vela show webservice --format markdown`

image

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**
CLI Version: master
Core Version: 0.1.0
GitRevision: git-d7f57ed1
GolangVersion: go1.17.7

**Cluster information**

**Additional context**

### PR DESCRIPTION
**Pull request by chivalryq**
Signed-off-by: qiaozp <qiaozhongpei.qzp@alibaba-inc.com>

### Description of your changes

```
docgen/GenrateReerenceDocs  (dm already init) ----> CreateMarkdown -> GenerateMakrdownForCap (Need DiscoveryMapper)
show/startReferenceDocsSite (add dm init here) --|
show/ShowReferenceMarkdown (add dm init here)  --|
```

Fixes #4697

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

Add e2e test for markdown format

### CODE REVIEW

**Review by wonderflow — APPROVED** [review]

File: references/cli/show.go [hunk 1]
```diff
@@ -186,6 +186,10 @@ func startReferenceDocsSite(ctx context.Context, ns string, c common.Args, ioStr
 	if err != nil {
 		return err
 	}
+	ref.DiscoveryMapper, err = c.GetDiscoveryMapper()
```
Comment (barnettZQG) [inline references/cli/show.go:189]: Advices move this code to before L174.

**Review by wonderflow — APPROVED** [review]
