### PR TITLE
Fix: add supported but missing provider

### LINKED ISSUE #4644: [Bug] terraform provider vsphere not supported when using vela def init
**Describe the bug**

Refer to https://github.com/kubevela/terraform-controller#supported-cloud-providers, `vsphere` as a terraform provider has been supported by terraform controller. But when using `vela def init` to [create the ComponentDefinition](https://kubevela.net/docs/platform-engineers/components/component-terraform), It got following error.

```shell
$ vela def init vsphere-file --type component --provider vsphere --desc "Terraform configuration for VMware vSphere File" --local ./vsphere_file.tf
Error: failed to generate Terraform typed component definition: Provider `vsphere` is not supported. Only `alibaba`, `aws`, `azure`, `gcp`, `baidu`, `tencent`, `elastic`, `ucloud` are supported.
failed to generate Terraform typed component definition: Provider `vsphere` is not supported. Only `alibaba`, `aws`, `azure`, `gcp`, `baidu`, `tencent`, `elastic`, `ucloud` are supported.
```

**KubeVela Version**

```shell
$ vela version
CLI Version: v1.4.8
Core Version: v1.4.8
GitRevision: git-192dc89
GolangVersion: go1.17.12
```

### PR DESCRIPTION
**Pull request by lunarwhite**
### Description of your changes

Fixes #4644

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

**Review by wonderflow — APPROVED** [review]

**Review by chivalryq — APPROVED** [review]

File: references/cli/def.go [hunk 1]
```diff
@@ -303,7 +303,7 @@ func generateTerraformTypedComponentDefinition(cmd *cobra.Command, name, kind, p
 	}
 
 	switch provider {
-	case "aws", "azure", "alibaba", "tencent", "gcp", "baidu", "elastic", "ucloud":
+	case "aws", "azure", "alibaba", "tencent", "gcp", "baidu", "elastic", "ucloud", "vsphere":
```
Comment (barnettZQG) [inline references/cli/def.go:306]: Provide a proposal to get the supported types dynamically:

The terraform controller writes a secret and CLI reads the  supported provider type list from this secret

**Review by Somefive — APPROVED** [review]
