### PR TITLE
Fix: useless log when enabling addon

### LINKED ISSUE #4614: Useless log when enabling addon
**Describe the bug**

When enable addon in cluster without gateway CRDs addon is enabled successfully. But there are some useless error logs. Like tt was searching the addon access endpoint. 

```shell
$ vela addon enable addons/terraform
enable addon by local dir: addons/terraform
W0812 17:24:33.366555   25297 render.go:194] Application name terraform will be overwritten with addon-terraform. Consider removing metadata.name in template.
Addon terraform enabled successfully.
^R
GGGjI0812 17:24:53.074527   25297 utils.go:156] find cluster gateway service vela-system/kubevela-cluster-gateway-service:9443
E0812 17:25:00.824934   25297 tree.go:822] error to list sub-resources: HTTPRoute err: no matches for kind "HTTPRoute" in version "gateway.networking.k8s.io/v1alpha2"
E0812 17:25:02.341743   25297 tree.go:822] error to list sub-resources: Gateway err: no matches for kind "Gateway" in version "gateway.networking.k8s.io/v1alpha2"
```

**To Reproduce**

1. `velad install`
2.  `vela addon enable terraform`

**Expected behavior**

No error logs

**Screenshots**

**KubeVela Version**

v1.5.0

**Cluster information**

**Additional context**

### PR DESCRIPTION
**Pull request by loheagn**
### Description of your changes

Change the logging level of `error to list sub-resources` from "error" to "warning".

Fixes #4614 

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [x] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

This PR just changes the logging level. No need to add extra tests.

### CODE REVIEW

File: pkg/velaql/providers/query/tree.go [hunk 1]
```diff
@@ -820,7 +820,7 @@ func iterateListSubResources(ctx context.Context, cluster string, k8sClient clie
 			items, err := listItemByRule(clusterCTX, k8sClient, resource, *parentObject, specifiedFunc, rule.DefaultGenListOptionFunc, rule.DisableFilterByOwnerReference)
 			if err != nil {
 				if meta.IsNoMatchError(err) || runtime.IsNotRegisteredError(err) {
-					klog.Errorf("error to list sub-resources: %s err: %v", resource.Kind, err)
+					klog.Warningf("error to list sub-resources: %s err: %v", resource.Kind, err)
```
Comment (chivalryq) [inline pkg/velaql/providers/query/tree.go:823]: maybe use "not listing sub-resources %s ..." to make this warning weaker.

**Comment by loheagn** [comment]
Hi, @chivalryq , I resolved the conversations. Please review the changes again :)

**Review by chivalryq — APPROVED** [review]
LGTM
