### PR TITLE
Fix: optimized the version comparison

### LINKED ISSUE #3950: Wrong version check for EKS clusters
**Describe the bug**

Wrong version check for EKS clusters.

`version v1.21.9-eks-14c7a48 require: >=v1.19`
**To Reproduce**

Set in metadata.yaml any kubernetes version check.
```
system:
  kubernetes: ">=v1.19"
```
From EKS cluster run `vela addon enable <addon>`.

**Expected behavior**

Addon installed.

**Screenshots**

image

**KubeVela Version**
v1.21.9

**Cluster information**

**Additional context**

### PR DESCRIPTION
**Pull request by barnettZQG**
Signed-off-by: barnettZQG <barnett.zqg@gmail.com>

### Description of your changes

```
Error: addon terraform-alibaba system requirement miss match: vela cli/ux version: v1.4.0-beta.1  require: >=v1.3.0
 addon terraform-alibaba cannot enable 
```

If can not compare the version with beta or alpha, try to remove the suffix and make it as pass as possible.

Fixes #3950

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### Special notes for your reviewer

/cc @wangyikewxgm

### CODE REVIEW

File: pkg/addon/addon.go [hunk 1]
```diff
@@ -1418,13 +1419,29 @@ func checkSemVer(actual string, require string) (bool, error) {
...
 	}
-	return constraint.Check(v), nil
+	if constraint.Check(v) {
+		return true, nil
+	}
+	if strings.Contains(actual, "-") {
+		smeVer := strings.TrimPrefix(actual[:strings.Index(actual, "-")], "v")
+		v, err := semver.NewVersion(smeVer)
+		if err != nil {
+			log.Logger.Errorf("fail to new version %s: %s", smeVer, err.Error())
```
Comment (wangyikewxgm) [inline pkg/addon/addon.go:1437]: check (version is :1.2.4-beta.2 constraint: >=1.2.4-beta.3) will get wrong check result ?

Comment (barnettZQG) [reply pkg/addon/addon.go:1437]: Fixed

**Comment by wangyikewxgm** [comment]
LGTM

**Review by wangyikewxgm — APPROVED** [review]

**Comment by wonderflow** [comment]
does it fixes #3950？

**Review by wonderflow — APPROVED** [review]

**Comment by barnettZQG** [comment]
> does it fixes #3950？

Yes, it also fixes
