### PR TITLE
Fix: api not exist don't break whole query process

### LINKED ISSUE #4128: topological graph can't show the service in the remote cluster
**Describe the bug**

I create the app in the local and remote cluster ,topological graph can show the service and deployment  in the local cluster,but 
topological graph can't show the service topological graph,only show the deployment topological graph;
EDCF7FE0-50E1-4896-B764-1EE7C7F325A9
local
remote
error
query  
/api/v1/query?velaql=application-resource-tree-view%7BappNs%3Ddefault,+appName%3Dvirgo-web%7D.status
rsp:
```json{
	"resources": [{
			"apiVersion": "apps/v1",
			"cluster": "infra-test2",
			"component": "virgo-web-deeeeeeee",
			"deployVersion": "20220608015054770",
			"kind": "Deployment",
			"latest": true,
			"name": "virgo-web-deeeeeeee",
			"namespace": "infra-test2",
			"publishVersion": "workflow-infra-test2-20220608015054783",
			"resourceTree": {
				"apiVersion": "apps/v1",
				"cluster": "infra-test2",
				"creationTimestamp": "2022-06-07T09:44:10Z",
				"deletionTimestamp": "0001-01-01T00:00:00Z",
				"healthStatus": {
					"message": "",
					"reason": "",
					"statusCode": "Healthy"
				},
				"kind": "Deployment",
				"leafNodes": [{
					"apiVersion": "apps/v1",
					"cluster": "infra-test2",
					"creationTimestamp": "2022-06-07T09:44:10Z",
					"deletionTimestamp": "0001-01-01T00:00:00Z",
					"healthStatus": {
						"message": "",
						"reason": "",
						"statusCode": "Healthy"
					},
					"kind": "ReplicaSet",
					"leafNodes": [{
						"additionalInfo": {
							"Age": "17h",
							"Ready": "1/1",
							"Restarts": 0,
							"Status": "Running"
						},
						"apiVersion": "v1",
						"cluster": "infra-test2",
						"creationTimestamp": "2022-06-07T09:44:10Z",
						"deletionTimestamp": "0001-01-01T00:00:00Z",
						"healthStatus": {
							"message": "",
							"reason": "all containers are ready",
							"statusCode": "Healthy"
						},
						"kind": "Pod",
						"name": "virgo-web-deeeeeeee-748c968c-j9djc",
						"namespace": "infra-test2",
						"uid": "48648065-acba-429d-9cfc-a87009dce705"
					}],
					"name": "virgo-web-deeeeeeee-748c968c",
					"namespace": "infra-test2",
					"uid": "9bbed776-7a64-4589-922f-f8c40b63b7b5"
				}],
				"name": "virgo-web-deeeeeeee",
				"namespace": "infra-test2"
			},
			"revision": "virgo-web-v2",
			"trait": ""
		},
		{
			"apiVersion": "v1",
			"cluster": "infra-test2",
			"component": "virgo-web-deeeeeeee",
			"deployVersion": "20220608015054770",
			"kind": "Service",
			"latest": true,
			"name": "virgo-web-deeeeeeee",
			"namespace": "infra-test2",
			"publishVersion": "workflow-infra-test2-20220608015054783",
			"revision": "virgo-web-v2",
			"trait": "AuxiliaryWorkload"
		},
		{
			"apiVersion": "apps/v1",
			"cluster": "infra-test2",
			"component": "virgo-web",
			"deployVersion": "20220608015054770",
			"kind": "Deployment",
			"latest": true,
			"name": "virgo-web",
			"namespace": "infra-test2",
			"publishVersion": "workflow-infra-test2-20220608015054783",
			"resourceTree": {
				"apiVersion": "apps/v1",
				"cluster": "infra-test2",
				"creationTimestamp": "2022-06-07T09:08:48Z",
				"deletionTimestamp": "0001-01-01T00:00:00Z",
				"healthStatus": {
					"message": "",
					"reason": "",
					"statusCode": "Healthy"
				},
				"kind": "Deployment",
				"leafNodes": [{
					"apiVersion": "apps/v1",
					"cluster": "infra-test2",
					"creationTimestamp": "2022-06-07T09:08:48Z",
					"deletionTimestamp": "0001-01-01T00:00:00Z",
					"healthStatus": {
						"message": "",
						"reason": "",
						"statusCode": "Healthy"
					},
					"kind": "ReplicaSet",
					"leafNodes": [{
						"additionalInfo": {
							"Age": "18h",
							"Ready": "1/1",
							"Restarts": 0,
							"Status": "Running"
						},
						"apiVersion": "v1",
						"cluster": "infra-test2",
						"creationTimestamp": "2022-06-07T09:08:48Z",
						"deletionTimestamp": "0001-01-01T00:00:00Z",
						"healthStatus": {
							"message": "",
							"reason": "all containers are ready",
							"statusCode": "Healthy"
						},
						"kind": "Pod",
						"name": "virgo-web-f97644cf9-v9pf6",
						"namespace": "infra-test2",
						"uid": "b247ebbd-083b-4c4a-9737-aeccfbd53fc9"
					}],
					"name": "virgo-web-f97644cf9",
					"namespace": "infra-test2",
					"uid": "da6510e7-cf75-4121-bcca-8907585a0266"
				}],
				"name": "virgo-web",
				"namespace": "infra-test2"
			},
			"revision": "virgo-web-v2",
			"trait": ""
		},
		{
			"apiVersion": "v1",
			"cluster": "infra-test2",
			"component": "virgo-web",
			"deployVersion": "20220608015054770",
			"kind": "Service",
			"latest": true,
			"name": "virgo-web",
			"namespace": "infra-test2",
			"publishVersion": "workflow-infra-test2-20220608015054783",
			"revision": "virgo-web-v2",
			"trait": "AuxiliaryWorkload"
		}
	]
}
```
debug  find   /api/v1/applications/virgo-web/components?envName=undefined

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**
CLI Version: v1.4.1
Core Version: 1.4.1
GitRevision: git-ea0508a
GolangVersion: go1.17.10

**Cluster information**

- local 1.20..11
- remote 1.16.6
**Additional context**
<!--

### PR DESCRIPTION
**Pull request by wangyikewxgm**
resourceTree more robust
Signed-off-by: 楚岳 <wangyike.wyk@alibaba-inc.com>

### Description of your changes

Fixes #4128 

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

File: pkg/velaql/providers/query/tree.go [hunk 1]
```diff
@@ -677,6 +678,9 @@ func iteratorChildResources(ctx context.Context, cluster string, k8sClient clien
 			clusterCTX := multicluster.ContextWithClusterName(ctx, cluster)
 			items, err := listItemByRule(clusterCTX, k8sClient, resource, *parentObject, specifiedFunc, rules.DefaultGenListOptionFunc)
 			if err != nil {
+				if meta.IsNoMatchError(err) || runtime.IsNotRegisteredError(err) {
```
Comment (barnettZQG) [inline pkg/velaql/providers/query/tree.go:681]: By analogy, are there any other errors that need to be ignored?

Comment (wangyikewxgm) [reply pkg/velaql/providers/query/tree.go:681]: Have considered this issue. IMO ignoring all error isn't proper.

**Review by barnettZQG — APPROVED** [review]
LGTM

**Review by wonderflow — APPROVED** [review]
