### PR TITLE
Fix: remove last-applied-config annotation for configmap and secret

### LINKED ISSUE #3938: vela reports error when apply configmap: annotations: Too long: must have at most 262144 bytes
**Describe the bug**

> Vela在apply一个Grafana面板的configmap的时候，有“metadata.annotations: Too long: must have at most 262144 bytes”的报错；这个用kubectl提交可以用kubectl replace去workaround

When submit a grafana configmap by using kubevela, it reports “metadata.annotations: Too long: must have at most 262144 bytes”.

This is also a common issue in kubectl, but we can use `kubectl replace` to workaround, in kubevela, how can I fix that?

**To Reproduce**

Write an application with long configmap nested by using `ref-objects` component type.

**Expected behavior**

We can have any work around to update the object.

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**

### PR DESCRIPTION
**Pull request by wonderflow**
Signed-off-by: Jianbo Sun <jianbo.sjb@alibaba-inc.com>

### Description of your changes

This PR remove the last-applied-config annotation for configmap and secret, and allow users to disable it by fill `-` or `skip` into this annotation `app.oam.dev/last-applied-configuration`.

You can disable it by adding a annotation triat, or manuelly add this annotation on it.

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: oamdev/hello-world
        ports:
         - port: 8000
           expose: true
      traits:
        - type: annotations
          properties:
            app.oam.dev/last-applied-configuration: skip
```

Then the deployment won't have the `app.oam.dev/last-applied-configuration` filled:

image

Fixes #3938

I have:

- [ ] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

File: pkg/utils/apply/apply.go [hunk 1]
```diff
@@ -107,13 +107,40 @@ func loggingApply(msg string, desired client.Object) {
...
+}
+
 // Apply applies new state to an object or create it if not exist
 func (a *APIApplicator) Apply(ctx context.Context, desired client.Object, ao ...ApplyOption) error {
 	_, err := generateRenderHash(desired)
 	if err != nil {
 		return err
 	}
-	applyAct := &applyAction{updateAnnotation: true}
+	fmt.Println("XXXXXXXXXXXXX", filterRecordForSpecial(desired))
```
Comment (leejanee) [inline pkg/utils/apply/apply.go:142]: debug print？

**Review by leejanee — APPROVED** [review]

File: pkg/utils/apply/apply.go (hunk 1 above)
Comment (wonderflow) [reply pkg/utils/apply/apply.go:142]: good catch, thanks

File: pkg/utils/apply/apply.go [hunk 2]
```diff
@@ -107,13 +107,39 @@ func loggingApply(msg string, desired client.Object) {
...
+}
+
 // Apply applies new state to an object or create it if not exist
 func (a *APIApplicator) Apply(ctx context.Context, desired client.Object, ao ...ApplyOption) error {
 	_, err := generateRenderHash(desired)
 	if err != nil {
 		return err
 	}
-	applyAct := &applyAction{updateAnnotation: true}
+	applyAct := &applyAction{updateAnnotation: filterRecordForSpecial(desired)}
```
Comment (barnettZQG) [inline pkg/utils/apply/apply.go:142]: There is an ApplyOption with the name DisableUpdateAnnotation, can we use this option?

Comment (wonderflow) [reply pkg/utils/apply/apply.go:142]: I know that option, but this is an initial and default behavior in this case

**Review by barnettZQG — APPROVED** [review]
