### PR TITLE
Fix: json-patch & json-merge-patch open result

### LINKED ISSUE #4221: some trait error, maybe conflict
**Describe the bug**

```
Applying an application in vela K8s object format...
I0622 15:38:13.992143   13292 apply.go:107] "patching object" name="platuml-server" resource="core.oam.dev/v1beta1, Kind=Application"
error: cannot patch object: admission webhook "validating.core.oam.dev.v1beta1.applications" denied the request: field "schematic": Invalid value error encountered, cannot evaluate trait "env": invalid patch trait env 
into workload: result check err: spec.template.spec.containers.0.env: conflicting list lengths: invalid value 1 (out of bound int & >=2).
```

**To Reproduce**

**Expected behavior**

```
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: platuml-server
  namespace: default
spec:
  components:
    - name: platuml-server
      type: webservice
      properties:
        image: plantuml/plantuml-server:jetty
        env:
        - name: TZ
          value: Asia/Shanghai
        ports:
        - name: http
          port: 8080
          expose: true
      traits:
        - type: annotations
          properties:
            app.kubernetes.io/tier: backend
        - type: env
          properties:
            env: 
              HI: Vela
        - type: storage
          properties:
            emptyDir:
              - name: jvm
                mountPath: /jvm
        - type: container-image
          properties:
            image: plantuml/plantuml-server:tomcat
            imagePullPolicy: IfNotPresent
```

**Screenshots**

**KubeVela Version**

```
CLI Version: v1.4.3
Core Version: 1.4.3
GitRevision: git-5e3ab73
GolangVersion: go1.17.11
```

**Cluster information**

**Additional context**

### PR DESCRIPTION
**Pull request by Somefive**
Signed-off-by: Somefive <yd219913@alibaba-inc.com>

### Description of your changes

JsonPatch and JsonMergePatch will close the patched result which will cause following cue trait patch failed. So before this PR, traits like `annotations` that uses the JsonPatch or JsonMergePatch must be placed after other patch trait.

Partially fixes #4221.

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

File: pkg/cue/model/sets/operation.go [hunk 1]
```diff
@@ -300,6 +300,9 @@ func strategyUnify(baseFile *ast.File, patchFile *ast.File, params *UnifyParams,
 		return jsonPatch(baseInst.Value(), patchInst.Lookup("operations"))
 	}
 
+	a, _ := toString(baseInst.Value())
```
Comment (FogDong) [inline pkg/cue/model/sets/operation.go:303]: test codes?

Comment (Somefive) [reply pkg/cue/model/sets/operation.go:303]: Sorry for that. :)
