### PR TITLE
Fix: vela status endpoint report error with k8s 1.24

### LINKED ISSUE #5008: velaux1.6 with domain setting not work
use vela addon enable velaux domain=velaux.xxx deploy ux , get error 
```
E1105 10:19:27.244493   18216 endpoint.go:114] no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"find v1 Ingress velaux/vela-system from cluster local failure
```
my cluster info
```
(base) reckless@reckless-ubuntu:~$ kc version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-14T02:36:39Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6", GitCommit:"b39bf148cd654599a52e867485c02c4f9d28b312", GitTreeState:"clean", BuildDate:"2022-09-21T13:12:04Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/amd64"}
```
ingress info
```
(base) reckless@reckless-ubuntu:~$ kc get ingress demo-localhost -o yaml
apiVersion: networking.k8s.io/v1
```
 error happend here?
https://github.com/kubevela/kubevela/blob/master/vela-templates/definitions/internal/trait/gateway.cue#L58

### PR DESCRIPTION
**Pull request by wangyikewxgm**
vela status endpoint report error with k8s 1.24

Signed-off-by: 楚岳 <wangyike.wyk@alibaba-inc.com>

### Description of your changes

Fixes #5008 

I have:

- [ ] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

File: pkg/velaql/providers/query/endpoint.go [hunk 1]
```diff
@@ -108,7 +109,7 @@ func getServiceEndpoints(ctx context.Context, cli client.Client, gvk schema.Grou
 	switch gvk.Kind {
 	case "Ingress":
 		if gvk.Group == networkv1beta1.GroupName && (gvk.Version == "v1beta1" || gvk.Version == "v1") {
-			var ingress networkv1beta1.Ingress
+			var ingress v1.Ingress
```
Comment (barnettZQG) [inline pkg/velaql/providers/query/endpoint.go:112]: Do we need to support versions before v1.19?

Comment (wangyikewxgm) [reply pkg/velaql/providers/query/endpoint.go:112]: Discussed with @wonderflow, we think it's needn't.

**Review by Somefive — APPROVED** [review]

**Review by wonderflow — APPROVED** [review]
