### PR TITLE
Fix: update namespace only if it doesn't have the env label

### LINKED ISSUE #4929: [Bug] 'vela env init' occasionally reports an error
**Describe the bug**

'vela env init' occasionally reports an error as "Operation cannot be fulfilled on namespaces "prod": the object has been modified; please apply your changes to the latest version and try again", but actually env was created successfully.
image
image

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**
1.5.6, 1.5.7

**Cluster information**
1.21.5

**Additional context**

### PR DESCRIPTION
**Pull request by nuclearwu**
Signed-off-by: wuzhongjian <wuzhongjian_yewu@cmss.chinamobile.com>

### Description of your changes
update namespace only if it doesn't have the env label

Fixes #4929 

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

**Review by Somefive — APPROVED** [review]

File: pkg/utils/k8s.go [hunk 1]
```diff
@@ -78,10 +78,11 @@ func MergeNoConflictLabels(labels map[string]string) MutateOption {
...
 func CreateOrUpdateNamespace(ctx context.Context, kubeClient client.Client, name string, options ...MutateOption) error {
 	err := CreateNamespace(ctx, kubeClient, name, options...)
-	if err != nil && !apierrors.IsAlreadyExists(err) {
-		return err
+	// only if namespace don't have the env label that we need to update it
+	if err != nil && apierrors.IsAlreadyExists(err) {
+		return UpdateNamespace(ctx, kubeClient, name, options...)
 	}
-	return UpdateNamespace(ctx, kubeClient, name, options...)
+	return err
```
Comment (wonderflow) [inline pkg/utils/k8s.go:85]:
```
	// only if namespace don't have the env label that we need to update it
	if apierrors.IsAlreadyExists(err) {
		return UpdateNamespace(ctx, kubeClient, name, options...)
	}
	return err
```

Comment (nuclearwu) [reply pkg/utils/k8s.go]: ok, done
