### PR TITLE
Fix: The log printing error for the addon module

### LINKED ISSUE #6206: [Bug] The log printing error for the addon module
**Describe the bug**

When using the helm repository as an addon repository, if some charts in the helm repository are not addons, they will also be printed as addon in the log.

**To Reproduce**

**Expected behavior**

Only the addons  in the helm repository are printed in the log

**Screenshots**

image
Only istio is an addon.
**KubeVela Version**

**Cluster information**

**Additional context**

### PR DESCRIPTION
**Pull request by suwliang3**
### Summary
📝🛠️🔥

Enhance logging of addon loading process. Refactor `pkg/addon/versioned_registry.go` to avoid unnecessary or empty log entries.

> _`addon` loading_
> _from versioned registry_
> _logs better in fall_

### Walkthrough
* Remove redundant log message for addon name and version ([link](https://github.com/kubevela/kubevela/pull/6207/files?diff=unified&w=0#diff-26be8587c8d145547594a37dcbeee70c0cac6de8616038a07b2e9637acc73085L164))
* Add condition to check for empty addon name before logging success ([link](https://github.com/kubevela/kubevela/pull/6207/files?diff=unified&w=0#diff-26be8587c8d145547594a37dcbeee70c0cac6de8616038a07b2e9637acc73085L189-R190))

Fixes #6206 

I have:

- [ ] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

File: pkg/addon/versioned_registry.go [hunk 1]
```diff
@@ -161,7 +161,6 @@ func (i versionedRegistry) loadAddon(ctx context.Context, name, version string)
 	if addonVersion == nil {
 		return nil, errors.Errorf("specified version %s not exist", utils.Sanitize(version))
 	}
-	klog.V(5).Infof("Addon '%s' with version '%s' found from registry '%s'", addonVersion.Name, addonVersion.Version, i.name)
```
Comment (wonderflow) [inline pkg/addon/versioned_registry.go:164]: we'd better filter addon in helm chart format in the `chooseVersion` function instead of remove the log directly.

do we have any special label to identity an addon from helm chart structure？ \cc @wangyikewxgm

Comment (wangyikewxgm) [reply pkg/addon/versioned_registry.go:164]: Not yet.

**Review by wangyikewxgm — APPROVED** [review]
