### PR TITLE
Fix: render addon application checkDeployClusters invalid

### LINKED ISSUE #5554: checking for cluster existence invalid when enable rollout addon on a nonexistent cluster
**Describe the bug**
checking for cluster existence invalid when enable rollout addon on a nonexistent cluster. this check is valid in old version.

the old version check:
image

**To Reproduce**
1. vela addon enable rollout --clusters={b,a}

**Expected behavior**
throw exception: Error: render addon application fail: cluster b not exist

**Screenshots**
image

**KubeVela Version**

1.7.4

**Cluster information**
1.21.5

### PR DESCRIPTION
**Pull request by zhaohuiweixiao**
### Description of your changes

Fixes #5554 

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

vela addon enable rollout --clusters={b,a}

### Special notes for your reviewer

@wangyikewxgm

### CODE REVIEW

File: pkg/addon/addon.go [hunk 1]
```diff
@@ -599,10 +599,18 @@ func getClusters(args map[string]interface{}) []string {
...
+		return cc
+	}
+	ccrslice, ok := ccr.([]interface{})
 	if !ok {
 		return nil
 	}
-	return cc
+	ccstring := make([]string, len(ccrslice))
+	for i := range ccrslice {
+		ccstring[i] = ccrslice[i].(string)
```
Comment (charlie0129) [inline pkg/addon/addon.go:611]: Although it may not happen, we should skip the items that cannot be converted to string, just in case.

**Review by wangyikewxgm — APPROVED** [review]
LGTM

**Review by wonderflow — APPROVED** [review]
GOOD JOB! Please fix CI.

**Comment by zhaohuiweixiao** [comment]
> GOOD JOB! Please fix CI.

@wonderflow the ci error was not introduced by my code.
