### PR TITLE
Fix: addon args is not changed when reinstall it without args

### LINKED ISSUE #6064: addon args value is not changed when reinstall it without args
**Describe the bug**
addon args value is not changed when reinstall it without args.

**To Reproduce**
1、vela addon enable fluxcd --clusters={local}
2、vela addon enable fluxcd

**Expected behavior**

fluxcd clusters value is nil

**Screenshots**

image

**KubeVela Version**
1.6.5

### PR DESCRIPTION
**Pull request by zhaohuiweixiao**
### Summary
🗑️🧩🔧

Add feature to uninstall addons by deleting secret file. Modify `pkg/addon/addon.go` to delete the secret file that stores the addon's arguments when uninstalling an addon.

> _`deleteArgsSecret`_
> _Uninstalling addons now_
> _Autumn leaves fall fast_

### Walkthrough
*  Add a function to delete the secret file for addon arguments (`[link](https://github.com/kubevela/kubevela/pull/6065/files?diff=unified&w=0#diff-dfc3f6e3b7231b7b41cf82b8e561f3cbf8191d214886e21d798f287f693806dbR847-R858)` in `pkg/addon/addon.go`)

Fixes #6064

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

1、vela addon enable fluxcd --clusters={local}
2、vela addon enable fluxcd

### Special notes for your reviewer
@wangyikewxgm

### CODE REVIEW

**Comment by Somefive** [comment]
Can we leave out an arg like "vela addon enable --reset-values" to make this issue work?

For example, in helm, when we run "helm upgrade", it will keep the parameters for the previous installation by default, which is "vela addon" currently follows. You can checkout the parameters in "helm upgrade -h".

```shell
      --reset-values                               when upgrading, reset the values to the ones built into the chart
      --reuse-values                               when upgrading, reuse the last release's values and merge in any overrides from the command line via --set and -f. If '--reset-values' is specified, this is ignored
```

**Comment by zhaohuiweixiao** [comment]
> Can we leave out an arg like "vela addon enable --reset-values" to make this issue work?
> 
> For example, in helm, when we run "helm upgrade", it will keep the parameters for the previous installation by default, which is "vela addon" currently follows. You can checkout the parameters in "helm upgrade -h".
> 
> ```shell
>       --reset-values                               when upgrading, reset the values to the ones built into the chart
>       --reuse-values                               when upgrading, reuse the last release's values and merge in any overrides from the command line via --set and -f. If '--reset-values' is specified, this is ignored
> ```

@Somefive ，But now this is not only a problem when upgrading, but also when reinstalling. when run `vela addon enable fluxcd --clusters={local}` first, then run `vela addon enable fluxcd`, the parameter file previous installation is also be retained.

**Comment by Somefive** [comment]
> > Can we leave out an arg like "vela addon enable --reset-values" to make this issue work?
> > For example, in helm, when we run "helm upgrade", it will keep the parameters for the previous installation by default, which is "vela addon" currently follows. You can checkout the parameters in "helm upgrade -h".
> > ```shell
> >       --reset-values                               when upgrading, reset the values to the ones built into the chart
> >       --reuse-values                               when upgrading, reuse the last release's values and merge in any overrides from the command line via --set and -f. If '--reset-values' is specified, this is ignored
> > ```
> 
> @Somefive ，But now this is not only a problem when upgrading, but also when reinstalling. when run `vela addon enable fluxcd --clusters={local}` first, then run `vela addon enable fluxcd`, the parameter file previous installation is also be retained.

You mean `vela addon enable fluxcd --clusters={local}`  -> `vela addon disable fluxcd` -> `vela addon enable fluxcd`? Is there a disable operation?

**Review by Somefive — APPROVED** [review]
Sounds reasonable for me now. I'm okay with this change.

File: pkg/addon/addon.go [hunk 1]
```diff
@@ -844,6 +844,18 @@ func RenderArgsSecret(addon *InstallPackage, args map[string]interface{}) *unstr
...
+	var sec v1.Secret
+	err := k8sClient.Get(ctx, client.ObjectKey{Namespace: types.DefaultKubeVelaNS, Name: addonutil.Addon2SecName(addonName)}, &sec)
+	if err == nil {
+		err = k8sClient.Delete(ctx, &sec)
+		if err != nil {
+			fmt.Printf("fail to delete %v addon parameter file", addonName)
+		}
+	}
+}
+
```
Comment (wangyikewxgm) [inline pkg/addon/addon.go:858]: If the error returned from the `get` function is not `errorNotFound`, please return the error.

It's highly recommended to handle this logic using the following pattern:
```
if err := k8sClient.Get(xxx); err == nil {
    // Handle successful get operation
} else {
    // Handle error
    if err != errorNotFound {
        return err
    }
}
```

**Review by wangyikewxgm — APPROVED** [review]
