### PR TITLE
Fix: error message of `vela init env` is not clear

### LINKED ISSUE #3947: [Bug] `vela env init env-application` return an error
**Describe the bug**

1e171e819b670f18c9a27802268848d

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**
vela cli 1.3.3
vela core 1.3.3

**Cluster information**

Kubernetes Version 1.20
**Additional context**

The error message is not clear, and confuses me

### PR DESCRIPTION
**Pull request by fourierr**
Signed-off-by: Xiangbo Ma <maxiangboo@cmbchina.com>

### Description of your changes

Fixes #3947
Error message of `vela init env` is not clear
I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [x] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

File: pkg/utils/env/env.go [hunk 1]
```diff
@@ -69,6 +69,14 @@ func CreateEnv(envArgs *types.EnvMeta) error {
 			return err
 		}
 	}
+	namespace, err := utils.GetNamespace(context.TODO(), c, envArgs.Namespace)
```
Comment (wonderflow) [inline pkg/utils/env/env.go:72]: let's unify the context with below one

**Review by wonderflow — COMMENTED** [review]
please increase the test coverage

**Comment by fourierr** [comment]
> please increase the test coverage

ok

**Review by barnettZQG — APPROVED** [review]
LGTM
