### PR TITLE
Fix: The resource topology fails to display the pods under the job #5566

### LINKED ISSUE #5566: The resource topology fails to display the pods under the job
**Describe the bug**
When the component is a task type, the resource topology map in the running state cannot display the pod associated with the job。

**To Reproduce**

**Expected behavior**
Under the resource topology, the job can display its associated pod

**Screenshots**

**KubeVela Version**
1.6.4

**Cluster information**
v1.19.9

**Additional context**

### PR DESCRIPTION
**Pull request by msun1996**
### Description of your changes

Fixes #5566

I have:

- [ ] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

I have carried out local debugging to verify this function, and it can normally solve the display problem of the job-associated pod under the resource topology

### CODE REVIEW

File: pkg/velaql/providers/query/tree.go [hunk 1]
```diff
@@ -215,6 +215,15 @@ func init() {
 			}),
 			GroupResourceType: GroupResourceType{Group: "batch", Kind: "CronJob"},
 		},
+		ChildrenResourcesRule{
+			GroupResourceType: GroupResourceType{Group: "batch", Kind: "Job"},
+			SubResources: buildSubResources([]*SubResourceSelector{
+				{
+					ResourceType: ResourceType{APIVersion: "v1", Kind: "Pod"},
+					listOptions:  jobLabelListOption,
```
Comment (barnettZQG) [inline pkg/velaql/providers/query/tree.go:223]: I think the Job resource could use the `defaultWorkloadLabelListOption`.

Comment (msun1996) [reply pkg/velaql/providers/query/tree.go:223]: Yes, my reference is wrong. Check the k8s code and find that getPodsForJob uses "spec", "selector"

**Review by barnettZQG — APPROVED** [review]
LGTM
