### PR TITLE
Fix: add addon registry

### LINKED ISSUE #5645: [bug]  add addon registry failed
**Describe the bug**

when adding a addon repository of type git ,it will return `Error: unknown flag: --token`
image
image

**To Reproduce**

`vela addon registry add my-repo --type git --endpoint=xxxxx --path=experimental/addons --token=gxxxxx`

**Expected behavior**

Successfully add an addon registry my-repo

**Screenshots**

**KubeVela Version**

CLI Version: 1.7.4
Core Version: 1.7.4
GitRevision: git-f3cdbcf2
GolangVersion: go1.19.5
**Cluster information**

1.21
**Additional context**

### PR DESCRIPTION
**Pull request by suwliang3**
### Description of your changes

Fixes #5645 

I have:

- [ ] Read and followed KubeVela's [contribution process](https://github.com/kubevela/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/kubevela/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

replace `token` with `gitToken`
 vela addon registry add my-repo --type git --endpoint=https://git --path=experimental/addons --gitToken=ghp_T3

### CODE REVIEW

File: references/cli/addon-registry.go [hunk 1]
```diff
@@ -72,8 +72,8 @@ func NewAddAddonRegistryCommand(c common.Args, ioStreams cmdutil.IOStreams) *cob
 		Short: "Add an addon registry.",
 		Long:  "Add an addon registry.",
 		Example: `add a helm repo registry: vela addon registry add --type=helm my-repo --endpoint=<URL>
-add a github registry: vela addon registry add my-repo --type git --endpoint=<URL> --path=<ptah> --token=<git token>" 
-add a gitlab registry: vela addon registry add my-repo --type gitlab --endpoint=<URL> --gitlabRepoName=<repoName> --path=<path> --token=<git token>`,
+add a github registry: vela addon registry add my-repo --type git --endpoint=<URL> --path=<ptah> --GitToken=<git token>" 
+add a gitlab registry: vela addon registry add my-repo --type gitlab --endpoint=<URL> --gitlabRepoName=<repoName> --path=<path> --GitToken=<git token>`,
```
Comment (charlie0129) [inline references/cli/addon-registry.go:76]:
```suggestion
add a github registry: vela addon registry add my-repo --type git --endpoint=<URL> --path=<ptah> --gitToken=<git token>" 
add a gitlab registry: vela addon registry add my-repo --type gitlab --endpoint=<URL> --gitlabRepoName=<repoName> --path=<path> --gitToken=<git token>`,
```

**Review by wangyikewxgm — APPROVED** [review]
Good catch.

**Review by Somefive — APPROVED** [review]
